/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KimYoseph
 */
public class joinMember extends javax.swing.JFrame {
    
    
    /**
     * Creates new form joinMember
     */
    public joinMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        existDialog = new javax.swing.JDialog();
        existBtnExit = new javax.swing.JButton();
        existLblTxt = new javax.swing.JLabel();
        joinDialog = new javax.swing.JDialog();
        joinBtnExit = new javax.swing.JButton();
        joinLblTxt = new javax.swing.JLabel();
        confirmDialog = new javax.swing.JDialog();
        confirmLbl = new javax.swing.JLabel();
        confirmBtnExit = new javax.swing.JButton();
        pwCfDialog = new javax.swing.JDialog();
        pcBtnExit1 = new javax.swing.JButton();
        pcLblTxt1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        lblPwConfirm = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        idTxtFd = new javax.swing.JTextField();
        pwTxtFd = new javax.swing.JTextField();
        pwConfirmTxtFd = new javax.swing.JTextField();
        nameTxtFd = new javax.swing.JTextField();
        joinMemberBtn = new javax.swing.JButton();

        existBtnExit.setText("닫기");
        existBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existBtnExitActionPerformed(evt);
            }
        });

        existLblTxt.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        existLblTxt.setText("이미 존재하는 아이디 입니다");

        javax.swing.GroupLayout existDialogLayout = new javax.swing.GroupLayout(existDialog.getContentPane());
        existDialog.getContentPane().setLayout(existDialogLayout);
        existDialogLayout.setHorizontalGroup(
            existDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existDialogLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(existBtnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existDialogLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(existLblTxt)
                .addGap(59, 59, 59))
        );
        existDialogLayout.setVerticalGroup(
            existDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existDialogLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(existLblTxt)
                .addGap(18, 18, 18)
                .addComponent(existBtnExit)
                .addContainerGap())
        );

        joinBtnExit.setText("닫기");
        joinBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinBtnExitActionPerformed(evt);
            }
        });

        joinLblTxt.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        joinLblTxt.setText("회원가입에 성공했습니다");

        javax.swing.GroupLayout joinDialogLayout = new javax.swing.GroupLayout(joinDialog.getContentPane());
        joinDialog.getContentPane().setLayout(joinDialogLayout);
        joinDialogLayout.setHorizontalGroup(
            joinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinDialogLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(joinBtnExit)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(joinLblTxt)
                .addGap(62, 62, 62))
        );
        joinDialogLayout.setVerticalGroup(
            joinDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinDialogLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(joinLblTxt)
                .addGap(18, 18, 18)
                .addComponent(joinBtnExit)
                .addContainerGap())
        );

        confirmLbl.setText("빈칸 없이 채워주세요!");

        confirmBtnExit.setText("닫기");
        confirmBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmDialogLayout = new javax.swing.GroupLayout(confirmDialog.getContentPane());
        confirmDialog.getContentPane().setLayout(confirmDialogLayout);
        confirmDialogLayout.setHorizontalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(confirmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(confirmBtnExit)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        confirmDialogLayout.setVerticalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(confirmLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(confirmBtnExit)
                .addContainerGap())
        );

        pcBtnExit1.setText("닫기");
        pcBtnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcBtnExit1ActionPerformed(evt);
            }
        });

        pcLblTxt1.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        pcLblTxt1.setText("비밀번호가 일치 하지 않습니다");

        javax.swing.GroupLayout pwCfDialogLayout = new javax.swing.GroupLayout(pwCfDialog.getContentPane());
        pwCfDialog.getContentPane().setLayout(pwCfDialogLayout);
        pwCfDialogLayout.setHorizontalGroup(
            pwCfDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwCfDialogLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(pcBtnExit1)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwCfDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pcLblTxt1)
                .addGap(46, 46, 46))
        );
        pwCfDialogLayout.setVerticalGroup(
            pwCfDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwCfDialogLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(pcLblTxt1)
                .addGap(18, 18, 18)
                .addComponent(pcBtnExit1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("굴림체", 1, 14)); // NOI18N
        lblTitle.setText("회원 가입");

        lblId.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        lblId.setText("아이디");

        lblPw.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        lblPw.setText("비밀번호");

        lblPwConfirm.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        lblPwConfirm.setText("비밀번호 확인");

        lblName.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        lblName.setText("성명");

        joinMemberBtn.setText("회원 가입");
        joinMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinMemberBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPw)
                                    .addComponent(lblId)
                                    .addComponent(lblName))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPwConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwConfirmTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(joinMemberBtn)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPw))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwConfirmTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPwConfirm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addComponent(joinMemberBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinMemberBtnActionPerformed
       
        User user = new User();
        user.setUserId(idTxtFd.getText());
        user.setUserPw(pwTxtFd.getText());
        user.setUserName(nameTxtFd.getText());
        // 아이디, 비밀번호, 이름 빈칸 있는지 확인
        if(user.getUserId() == null || user.getUserPw() == null || user.getUserName() == null){           
            confirmDialog.setSize(300, 150);
            confirmDialog.setLocation(350, 350);
            confirmDialog.show();
        }else{
            // 비밀번호 == 비밀번호 확인 확인
            if(user.getUserPw().equals(pwConfirmTxtFd.getText())){
                userDAO UserDAO = new userDAO();
                
                int result = UserDAO.joinMember(user);
                if(result == -1){
                    existDialog.setSize(300, 150);
                    existDialog.setLocation(350, 350);
                    existDialog.show();
                }else{
                    joinDialog.setSize(300, 150);
                    joinDialog.setLocation(350, 350);
                    joinDialog.show();
                }
            }else{
                pwCfDialog.setSize(300, 150);
                pwCfDialog.setLocation(350, 350);
                pwCfDialog.show();
            }
        }
    }//GEN-LAST:event_joinMemberBtnActionPerformed

    private void existBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existBtnExitActionPerformed
        existDialog.dispose();
    }//GEN-LAST:event_existBtnExitActionPerformed

    private void joinBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinBtnExitActionPerformed
        joinDialog.dispose();
    }//GEN-LAST:event_joinBtnExitActionPerformed

    private void confirmBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnExitActionPerformed
        confirmDialog.dispose();
    }//GEN-LAST:event_confirmBtnExitActionPerformed

    private void pcBtnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcBtnExit1ActionPerformed
        pwCfDialog.dispose();
    }//GEN-LAST:event_pcBtnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(joinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(joinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(joinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(joinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new joinMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtnExit;
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JLabel confirmLbl;
    private javax.swing.JButton existBtnExit;
    private javax.swing.JDialog existDialog;
    private javax.swing.JLabel existLblTxt;
    private javax.swing.JTextField idTxtFd;
    private javax.swing.JButton joinBtnExit;
    private javax.swing.JDialog joinDialog;
    private javax.swing.JLabel joinLblTxt;
    private javax.swing.JButton joinMemberBtn;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPwConfirm;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField nameTxtFd;
    private javax.swing.JButton pcBtnExit1;
    private javax.swing.JLabel pcLblTxt1;
    private javax.swing.JDialog pwCfDialog;
    private javax.swing.JTextField pwConfirmTxtFd;
    private javax.swing.JTextField pwTxtFd;
    // End of variables declaration//GEN-END:variables
}
